spring.application.name=my_mcp

# ai mcp server
spring.ai.mcp.server.name=my_mcp
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=async
spring.ai.mcp.server.instructions="This server holds a meaningful and expandable list of colors"
spring.ai.mcp.server.sse-endpoint=/sse
spring.ai.mcp.server.capabilities.completion=true
spring.ai.mcp.server.capabilities.tool=true
spring.ai.mcp.server.capabilities.resource=true
spring.ai.mcp.server.capabilities.prompt=true


server.port=8080

spring.main.banner-mode=off
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx

management.endpoints.web.exposure.include=health,info,mappings
management.endpoint.mappings.access=read_only
